import { test } from 'node:test';
import assert from 'node:assert/strict';
import { candidateSchema, jobSchema, validateDocument } from '../server/validation';
const candidate = { firstName: ' Alex ', lastName: 'Morgan', email: 'ALEX@example.test', phone: '07700 900100', location: 'Manchester', currentJobTitle: 'Engineer', yearsExperience: '4', skills: 'React, TypeScript', qualifications: 'BSc', consent: 'true' };
test('normalises candidate email, names, experience and skills', () => { const result = candidateSchema.parse(candidate); assert.equal(result.email, 'alex@example.test'); assert.equal(result.firstName, 'Alex'); assert.equal(result.yearsExperience, 4); assert.deepEqual(result.skills, ['React', 'TypeScript']); });
test('requires consent and rejects invalid email and unsafe profile URL', () => { for (const patch of [{ consent: 'false' }, { email: 'invalid' }, { linkedinUrl: 'javascript:alert(1)' }, { yearsExperience: -1 }]) assert.equal(candidateSchema.safeParse({ ...candidate, ...patch }).success, false); });
test('validates document signature, type and maximum file size', () => { assert.equal(validateDocument('resume.pdf', 'application/pdf', Buffer.from('%PDF-1.7\n')), 'application/pdf'); assert.throws(() => validateDocument('resume.pdf', 'application/pdf', Buffer.from('<script>'))); assert.throws(() => validateDocument('resume.exe', 'application/pdf', Buffer.from('%PDF-'))); const oversized = Buffer.alloc(5 * 1024 * 1024 + 1); oversized.write('%PDF-'); assert.throws(() => validateDocument('resume.pdf', 'application/pdf', oversized)); assert.throws(() => validateDocument('resume.docx', 'application/octet-stream', Buffer.from('PK\u0003\u0004not a word document'))); });
const job = { title: 'Senior Engineer', location: 'Manchester', description: 'Build reliable software as part of a collaborative engineering team.', jobType: 'Permanent', experienceRequired: 'Senior', salaryMin: 50000, salaryMax: 70000, salaryText: null, salaryVisible: true, skills: ['TypeScript'], responsibilities: 'Build software.', requirements: 'Relevant experience.', benefits: null, closingDate: new Date(Date.now() + 86400000).toISOString(), status: 'OPEN' };
test('rejects reversed salary, unknown job types and expired published vacancies', () => { assert.equal(jobSchema.safeParse(job).success, true); for (const patch of [{ salaryMax: 10000 }, { jobType: 'Unconfigured' }, { closingDate: '2020-01-01T00:00:00.000Z' }]) assert.equal(jobSchema.safeParse({ ...job, ...patch }).success, false); assert.equal(jobSchema.safeParse({ ...job, status: 'DRAFT', closingDate: '2020-01-01T00:00:00.000Z' }).success, true); });
