import { z } from 'zod';
import { jobTypes, experienceLevels, jobStatuses, applicationStatuses } from '../src/lib/config';
const text = (min = 1, max = 200) => z.string().trim().min(min).max(max);
export const loginSchema = z.object({ email: z.email().max(254).transform(v => v.toLowerCase()), password: z.string().min(1).max(200) });
export const candidateSchema = z.object({ firstName: text(1, 80), lastName: text(1, 80), email: z.email().max(254).transform(v => v.toLowerCase()), phone: text(7, 30), location: text(), currentJobTitle: text(), yearsExperience: z.coerce.number().int().min(0).max(70), skills: text(1, 2000).transform(v => v.split(',').map(s => s.trim()).filter(Boolean)), qualifications: text(1, 5000), linkedinUrl: z.union([z.literal(''), z.url().max(500).refine(v => new URL(v).protocol === 'https:', 'Use an HTTPS URL')]).optional(), consent: z.literal('true'), jobId: text().optional() });
export const jobSchema = z.object({ title: text(3), location: text(), description: text(30, 20000), jobType: z.enum(jobTypes as [string, ...string[]]), experienceRequired: z.enum(experienceLevels as [string, ...string[]]), salaryMin: z.number().int().nonnegative().nullable(), salaryMax: z.number().int().nonnegative().nullable(), salaryText: z.string().trim().max(200).nullable(), salaryVisible: z.boolean(), skills: z.array(text(1, 100)).max(50), responsibilities: text(1, 10000), requirements: text(1, 10000), benefits: z.string().trim().max(10000).nullable(), closingDate: z.iso.datetime(), status: z.enum(jobStatuses) }).refine(v => v.salaryMin === null || v.salaryMax === null || v.salaryMax >= v.salaryMin, 'Maximum salary must be at least minimum salary').refine(v => v.status !== 'OPEN' || new Date(v.closingDate) > new Date(), 'Published jobs need a future closing date');
export const statusSchema = z.object({ status: z.enum(applicationStatuses) });
export const noteSchema = z.object({ body: text(1, 5000), applicationId: text().optional() });
export function validateDocument(name: string, mime: string, bytes: Buffer) {
  const ext = name.toLowerCase().split('.').pop();
  const valid = (ext === 'pdf' && mime === 'application/pdf' && bytes.subarray(0, 5).toString() === '%PDF-') || (ext === 'doc' && ['application/msword', 'application/octet-stream'].includes(mime) && bytes.subarray(0, 8).equals(Buffer.from('d0cf11e0a1b11ae1', 'hex'))) || (ext === 'docx' && ['application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/octet-stream'].includes(mime) && bytes.subarray(0, 4).equals(Buffer.from('504b0304', 'hex')) && bytes.includes(Buffer.from('[Content_Types].xml')) && bytes.includes(Buffer.from('word/')));
  if (!valid || bytes.length === 0 || bytes.length > 5 * 1024 * 1024) throw new Error('Upload a valid PDF, DOC or DOCX document up to 5 MB.');
  return ext === 'pdf' ? 'application/pdf' : ext === 'doc' ? 'application/msword' : 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
}
