import { useState } from 'react';
import { ArrowUpRight, Menu, X, ArrowRight, BriefcaseBusiness, LayoutDashboard, Users, Files, Settings, LogOut } from 'lucide-react';
import type { ReactNode } from 'react';
import { Logo, Link } from './ui';
import type { User } from '../types';
import { api } from '../api';
export function PublicHeader() { const [open, setOpen] = useState(false); const pathname = window.location.pathname; return <header className="public-header"><div className="container header-inner"><Logo/><nav className={open ? 'public-nav open' : 'public-nav'} aria-label="Main navigation">{[['/', 'Home'], ['/jobs', 'Find Jobs'], ['/about', 'About Us'], ['/contact', 'Contact']].map(([href, title]) => <Link key={href} href={href} className={pathname === href ? 'active' : ''}>{title}</Link>)}<Link href="/submit-cv" className="mobile-cv">Submit your CV</Link></nav><Link href="/jobs" className="button header-cta">Find your next role<ArrowUpRight size={16}/></Link><button className="icon-button menu-toggle" aria-label={open ? 'Close menu' : 'Open menu'} aria-expanded={open} onClick={() => setOpen(!open)}>{open ? <X/> : <Menu/>}</button></div></header>; }
export function Footer() { return <footer><div className="container footer-grid"><div><Logo/><p>Great talent. The right opportunity.<br/>A connection that makes a difference.</p></div><div><h4>Explore</h4><Link href="/jobs">Find a job</Link><Link href="/submit-cv">Submit your CV</Link><Link href="/about">About us</Link></div><div><h4>Let’s connect</h4><Link href="/contact">Contact our team <ArrowUpRight size={13}/></Link><span>Recruitment across the UK</span><Link href="/admin/login">Recruiter portal</Link></div><div className="footer-note"><span className="eyebrow">YOUR NEXT CHAPTER</span><h3>Starts with a<br/>connection.</h3><Link href="/jobs">Explore opportunities <ArrowRight size={16}/></Link></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Cosmic Connect. All rights reserved.</span><div><Link href="/privacy">Privacy policy</Link><Link href="/terms">Terms of use</Link></div></div></footer>; }
export function PublicLayout({ children }: { children: ReactNode }) { return <><a className="skip-link" href="#main">Skip to content</a><PublicHeader/><main id="main">{children}</main><Footer/></>; }
export function AdminLayout({ user, children }: { user: User; children: ReactNode }) { const [open, setOpen] = useState(false); const [error, setError] = useState(''); const pathname = window.location.pathname; const items = [['/admin', 'Dashboard', LayoutDashboard], ['/admin/jobs', 'Jobs', BriefcaseBusiness], ['/admin/candidates', 'Candidates', Users], ['/admin/applications', 'Applications', Files]] as const; return <div className="admin-shell"><aside className={`admin-sidebar ${open ? 'open' : ''}`}><Logo/><p className="sidebar-label">RECRUITMENT WORKSPACE</p><nav aria-label="Recruiter navigation">{items.map(([href, label, Icon]) => <Link key={href} href={href} className={(href === '/admin' ? pathname === href : pathname.startsWith(href)) ? 'active' : ''}><Icon size={19}/>{label}</Link>)}</nav><div className="sidebar-bottom"><Link href="/admin/settings"><Settings size={19}/>Settings</Link><button onClick={async () => { try { await api('/logout', { method: 'POST' }); window.location.assign('/admin/login'); } catch (e) { setError((e as Error).message); } }}><LogOut size={19}/>Log out</button>{error && <p role="alert">{error}</p>}<span>Cosmic Connect · Recruiter portal</span></div></aside><div className="admin-body"><header className="admin-topbar"><button className="icon-button menu-toggle" onClick={() => setOpen(!open)} aria-label="Toggle sidebar" aria-expanded={open}><Menu/></button><Link href="/" className="text-button">View website <ArrowUpRight size={15}/></Link><div className="user-chip"><span>{user.name.slice(0, 2).toUpperCase()}</span><div><strong>{user.name}</strong><small>{user.role.toLowerCase()}</small></div></div></header><main className="admin-content" id="main">{children}</main></div></div>; }
