import { useEffect, useRef, type ReactNode, type InputHTMLAttributes, type SelectHTMLAttributes, type TextareaHTMLAttributes } from 'react';
import { ArrowRight, BriefcaseBusiness, MapPin, ArrowUpRight, AlertCircle, LoaderCircle, X } from 'lucide-react';
import type { Job } from '../types';
import { date, human } from '../lib/config';
export function Link({ href, children, className = '', ...props }: { href: string; children: ReactNode; className?: string; title?: string; 'aria-label'?: string }) { return <a href={href} className={className} {...props}>{children}</a>; }
export function Logo({ light = false }: { light?: boolean }) {
  return <Link href="/" className={`logo ${light ? 'logo-light' : ''}`} aria-label="Cosmic Connect home"><svg className="brand-mark" viewBox="399 844 150 158" aria-hidden="true"><image href="/brand-reference.jpeg" width="945" height="2048"/></svg><span><strong>COSMIC</strong><small>CONNECT</small></span></Link>;
}
export function Field({ label, ...props }: InputHTMLAttributes<HTMLInputElement> & { label: string }) { return <label className="field"><span>{label}{props.required && <i aria-hidden="true"> *</i>}</span><input {...props}/></label>; }
export function Select({ label, children, ...props }: SelectHTMLAttributes<HTMLSelectElement> & { label: string }) { return <label className="field"><span>{label}</span><select {...props}>{children}</select></label>; }
export function Textarea({ label, ...props }: TextareaHTMLAttributes<HTMLTextAreaElement> & { label: string }) { return <label className="field"><span>{label}{props.required && <i aria-hidden="true"> *</i>}</span><textarea rows={4} {...props}/></label>; }
export function Badge({ status }: { status: string }) { return <span className={`badge badge-${status.toLowerCase()}`}>{human(status)}</span>; }
export function ErrorState({ message, retry }: { message: string; retry?: () => void }) { return <div className="message error" role="alert"><AlertCircle size={20}/><span>{message}</span>{retry && <button onClick={retry} className="text-button">Try again</button>}</div>; }
export function LoadingState() { return <div className="empty" role="status"><LoaderCircle className="spin"/> Loading…</div>; }
export function EmptyState({ message }: { message: string }) { return <div className="empty"><BriefcaseBusiness size={32}/><h3>{message}</h3><p>Try changing your search or check back soon.</p></div>; }
export function salary(j: Job) { if (!j.salaryVisible) return 'Salary on application'; if (j.salaryText) return j.salaryText; const format = (n: number) => '£' + n.toLocaleString('en-GB'); return j.salaryMin ? `${format(j.salaryMin)}${j.salaryMax ? ' – ' + format(j.salaryMax) : ''}` : 'Competitive salary'; }
export function JobCard({ job }: { job: Job }) {
  const icons = ['</>', 'PM', 'BA', 'RC', 'OC']; const index = Math.max(0, ['Senior Software Engineer', 'Project Manager', 'Business Analyst', 'Recruitment Consultant', 'Operations Coordinator'].indexOf(job.title));
  return <article className="job-card"><div className="job-card-top"><span className="job-icon">{icons[index]}</span><span className="pill">{job.jobType}</span></div><p className="eyebrow small">{job.skills[0] || 'Opportunity'}</p><h3><Link href={`/jobs/${job.slug}`}>{job.title}</Link></h3><div className="job-meta"><span><MapPin size={14}/>{job.location}</span><span className="meta-dot">•</span><span>{job.experienceRequired}</span></div><p className="job-excerpt">{job.description.split('. ')[0]}.</p><strong className="salary">{salary(job)}<small> / year</small></strong><div className="job-card-bottom"><span>{job.publishedAt ? `Posted ${date(job.publishedAt)}` : 'New opportunity'}</span><Link href={`/jobs/${job.slug}`} className="job-link" aria-label={`View ${job.title}`}><ArrowUpRight size={20}/></Link></div></article>;
}
export function SectionTitle({ eyebrow, title, text, children }: { eyebrow?: string; title: string; text?: string; children?: ReactNode }) { return <div className="section-title"><div>{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h2>{title}</h2>{text && <p>{text}</p>}</div>{children}</div>; }
export function ButtonLink({ href, children, secondary = false }: { href: string; children: ReactNode; secondary?: boolean }) { return <Link href={href} className={`button ${secondary ? 'secondary' : ''}`}>{children}<ArrowRight size={17}/></Link>; }
export function ConfirmDialog({ title, message, onConfirm, onCancel, busy }: { title: string; message: string; onConfirm: () => void; onCancel: () => void; busy?: boolean }) { const ref = useRef<HTMLDialogElement>(null); useEffect(() => { const dialog = ref.current; dialog?.showModal(); return () => dialog?.close(); }, []); return <dialog ref={ref} className="modal" aria-labelledby="confirm-title" onCancel={onCancel}><button className="icon-button modal-close" onClick={onCancel} aria-label="Close confirmation"><X/></button><h2 id="confirm-title">{title}</h2><p>{message}</p><div className="actions"><button onClick={onCancel} className="button secondary" autoFocus>Cancel</button><button onClick={onConfirm} disabled={busy} className="button danger">{busy ? 'Please wait…' : 'Confirm'}</button></div></dialog>; }
export function Toast({ message }: { message: string }) { return message ? <div role="status" className="toast">{message}</div> : null; }
