import { StrictMode, useEffect } from 'react';
import { createRoot } from 'react-dom/client';
import { PublicLayout, AdminLayout } from './components/layout';
import { Home, Jobs, JobDetail, InfoPage } from './pages/Public';
import { Apply } from './pages/Apply';
import { Login } from './pages/Login';
import { AdminDashboard, AdminJobs, AdminApplications, AdminCandidates, AdminJobDetail, ApplicationDetail, CandidateDetail, Settings } from './pages/Admin';
import { JobForm } from './pages/JobForm';
import { useApi } from './api';
import type { User } from './types';
import { LoadingState, ErrorState, Link } from './components/ui';
import './styles.css';
function App() { const path = window.location.pathname.replace(/\/$/, '') || '/'; useEffect(() => { const privatePage = /^\/(admin|apply|submit-cv)/.test(path); let meta = document.querySelector<HTMLMetaElement>('meta[name="robots"]'); if (!meta) { meta = document.createElement('meta'); meta.name = 'robots'; document.head.append(meta); } meta.content = privatePage ? 'noindex,nofollow' : 'index,follow'; document.title = `${path === '/' ? 'Connecting talent with opportunity' : path.startsWith('/admin') ? 'Recruiter portal' : path === '/jobs' ? 'Find your next opportunity' : 'Your next chapter'} | Cosmic Connect`; }, [path]); if (path === '/admin/login') return <Login/>; if (path.startsWith('/admin')) return <ProtectedAdmin path={path}/>; let page; if (path === '/') page = <Home/>; else if (path === '/jobs') page = <Jobs/>; else if (path.startsWith('/jobs/')) page = <JobDetail slug={decodeURIComponent(path.split('/')[2])}/>; else if (path.startsWith('/apply/')) page = <Apply jobId={path.split('/')[2]}/>; else if (path === '/submit-cv') page = <Apply/>; else if (['/about', '/contact', '/privacy', '/terms'].includes(path)) page = <InfoPage type={path.slice(1)}/>; else page = <div className="container section"><h1>This page hasn’t connected yet.</h1><p>The page you’re looking for could not be found.</p><Link href="/" className="button">Back to home</Link></div>; return <PublicLayout>{page}</PublicLayout>; }
function ProtectedAdmin({ path }: { path: string }) { const { data: user, loading, error } = useApi<User>('/session'); if (loading) return <LoadingState/>; if (!user) return <main className="login-side"><div><ErrorState message={error || 'Please sign in to continue.'}/><Link href="/admin/login" className="button">Sign in to recruiter portal</Link></div></main>; const parts = path.split('/'); let page; if (path === '/admin') page = <AdminDashboard/>; else if (path === '/admin/jobs') page = <AdminJobs/>; else if (path === '/admin/jobs/new') page = <JobForm/>; else if (parts[2] === 'jobs' && parts[4] === 'edit') page = <JobForm id={parts[3]}/>; else if (parts[2] === 'jobs' && parts[3]) page = <AdminJobDetail id={parts[3]}/>; else if (path === '/admin/applications') page = <AdminApplications/>; else if (parts[2] === 'applications' && parts[3]) page = <ApplicationDetail id={parts[3]}/>; else if (path === '/admin/candidates') page = <AdminCandidates/>; else if (parts[2] === 'candidates' && parts[3]) page = <CandidateDetail id={parts[3]} user={user}/>; else if (path === '/admin/settings') page = <Settings user={user}/>; else page = <ErrorState message="Page not found."/>; return <AdminLayout user={user}>{page}</AdminLayout>; }
createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>);
